#!/usr/bin/env python3
"""Require the hand-written modules from the gem entrypoint (FR-025).

The patches write errors.rb, retry.rb, pagination.rb and oauth.rb, and the generator's own
lib/flat_api.rb knows nothing about them. So `require 'flat_api'` loaded the generated client and
none of the surface built on top of it: FlatNotFoundError and the other typed errors, the retry
policy that understands Flat's 403 rate limiting, the Link-header pagination helper, and
OAuth2Helper. A caller following the README got `uninitialized constant FlatApi::FlatNotFoundError`.

Worse once the errors patch rewired api_client.rb, which calls FlatApi.error_from_response: without
the require that raises NameError at the moment an API error is being reported, replacing a useful
message with a confusing one.

Idempotent: inserts each require once, in a marked block, and rebuilds it on every run.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
ENTRY = ROOT / "lib" / "flat_api.rb"

BEGIN = "# BEGIN generated by tools/patches/95_requires.py"
END = "# END generated by tools/patches/95_requires.py"

# Order matters: errors is required before api_client, which raises from it. client comes last,
# since FlatClient names ApiClient, Configuration, Pagination and every generated *Api class.
MODULES = ["errors", "retry", "pagination", "oauth", "client"]

if not ENTRY.is_file():
    sys.exit("95_requires: lib/flat_api.rb is missing (FR-025)")

text = ENTRY.read_text()

# Drop any previous block, so this rebuilds rather than appends.
if BEGIN in text:
    head, rest = text.split(BEGIN, 1)
    text = head + rest.split(END, 1)[1].lstrip("\n")

missing = [m for m in MODULES if not (ROOT / "lib" / "flat_api" / f"{m}.rb").is_file()]
if missing:
    sys.exit(f"95_requires: patches did not write {', '.join(missing)} (FR-025)")

anchor = "require 'flat_api/api_client'\n"
if anchor not in text:
    sys.exit("95_requires: could not find the api_client require to anchor to (FR-025)")

block = "\n".join(
    [
        BEGIN,
        "# The ergonomic surface the patches add. errors comes first: api_client raises from it.",
        *[f"require 'flat_api/{m}'" for m in MODULES],
        END,
        "",
    ]
)
ENTRY.write_text(text.replace(anchor, block + anchor, 1))
print(f"    requires: {', '.join(MODULES)} wired into lib/flat_api.rb")
