=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.26.2
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module FlatApi
  # Capabilities the current user has on this assignment. Each capability corresponds to a fine-grained action that a user may take.
  class AssignmentCapabilities < ApiModelBase
    # Whether the current user can edit the assignment 
    attr_accessor :can_edit

    # Whether this assignment can be published in a class 
    attr_accessor :can_publish_in_class

    attr_accessor :can_publish_in_class_error

    # Whether the current user can archive the assignment 
    attr_accessor :can_archive

    # Whether the current user can unarchive the assignment 
    attr_accessor :can_unarchive

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'can_edit' => :'canEdit',
        :'can_publish_in_class' => :'canPublishInClass',
        :'can_publish_in_class_error' => :'canPublishInClassError',
        :'can_archive' => :'canArchive',
        :'can_unarchive' => :'canUnarchive'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'can_edit' => :'Boolean',
        :'can_publish_in_class' => :'Boolean',
        :'can_publish_in_class_error' => :'AssignmentCapabilitiesCanPublishInClassError',
        :'can_archive' => :'Boolean',
        :'can_unarchive' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::AssignmentCapabilities` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::AssignmentCapabilities`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'can_edit')
        self.can_edit = attributes[:'can_edit']
      else
        self.can_edit = nil
      end

      if attributes.key?(:'can_publish_in_class')
        self.can_publish_in_class = attributes[:'can_publish_in_class']
      else
        self.can_publish_in_class = nil
      end

      if attributes.key?(:'can_publish_in_class_error')
        self.can_publish_in_class_error = attributes[:'can_publish_in_class_error']
      end

      if attributes.key?(:'can_archive')
        self.can_archive = attributes[:'can_archive']
      else
        self.can_archive = nil
      end

      if attributes.key?(:'can_unarchive')
        self.can_unarchive = attributes[:'can_unarchive']
      else
        self.can_unarchive = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @can_edit.nil?
        invalid_properties.push('invalid value for "can_edit", can_edit cannot be nil.')
      end

      if @can_publish_in_class.nil?
        invalid_properties.push('invalid value for "can_publish_in_class", can_publish_in_class cannot be nil.')
      end

      if @can_archive.nil?
        invalid_properties.push('invalid value for "can_archive", can_archive cannot be nil.')
      end

      if @can_unarchive.nil?
        invalid_properties.push('invalid value for "can_unarchive", can_unarchive cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @can_edit.nil?
      return false if @can_publish_in_class.nil?
      return false if @can_archive.nil?
      return false if @can_unarchive.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] can_edit Value to be assigned
    def can_edit=(can_edit)
      if can_edit.nil?
        fail ArgumentError, 'can_edit cannot be nil'
      end

      @can_edit = can_edit
    end

    # Custom attribute writer method with validation
    # @param [Object] can_publish_in_class Value to be assigned
    def can_publish_in_class=(can_publish_in_class)
      if can_publish_in_class.nil?
        fail ArgumentError, 'can_publish_in_class cannot be nil'
      end

      @can_publish_in_class = can_publish_in_class
    end

    # Custom attribute writer method with validation
    # @param [Object] can_archive Value to be assigned
    def can_archive=(can_archive)
      if can_archive.nil?
        fail ArgumentError, 'can_archive cannot be nil'
      end

      @can_archive = can_archive
    end

    # Custom attribute writer method with validation
    # @param [Object] can_unarchive Value to be assigned
    def can_unarchive=(can_unarchive)
      if can_unarchive.nil?
        fail ArgumentError, 'can_unarchive cannot be nil'
      end

      @can_unarchive = can_unarchive
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          can_edit == o.can_edit &&
          can_publish_in_class == o.can_publish_in_class &&
          can_publish_in_class_error == o.can_publish_in_class_error &&
          can_archive == o.can_archive &&
          can_unarchive == o.can_unarchive
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [can_edit, can_publish_in_class, can_publish_in_class_error, can_archive, can_unarchive].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
