=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.20.0
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module FlatApi
  # A classroom
  class ClassDetails
    # The unique identifier of the class
    attr_accessor :id

    attr_accessor :state

    # The name of the class
    attr_accessor :name

    # The section of the class
    attr_accessor :section

    # An optionnal description for this class
    attr_accessor :description

    # The unique identifier of the Organization owning this class
    attr_accessor :organization

    # The unique identifier of the User owning this class
    attr_accessor :owner

    # The date when the class was create
    attr_accessor :creation_date

    # [Teachers only] The enrollment code that can be used by the students to join the class 
    attr_accessor :enrollment_code

    # The theme identifier using in Flat User Interface
    attr_accessor :theme

    # The number of assignments created in the class
    attr_accessor :assignments_count

    attr_accessor :students_group

    attr_accessor :teachers_group

    attr_accessor :issues

    attr_accessor :google_classroom

    attr_accessor :google_drive

    attr_accessor :microsoft_graph

    attr_accessor :lti

    attr_accessor :canvas

    attr_accessor :mfc

    attr_accessor :clever

    attr_accessor :level

    # Specific skills that will be focused in classroom
    attr_accessor :skills_focused

    # Number of students in the classroom
    attr_accessor :size

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'state' => :'state',
        :'name' => :'name',
        :'section' => :'section',
        :'description' => :'description',
        :'organization' => :'organization',
        :'owner' => :'owner',
        :'creation_date' => :'creationDate',
        :'enrollment_code' => :'enrollmentCode',
        :'theme' => :'theme',
        :'assignments_count' => :'assignmentsCount',
        :'students_group' => :'studentsGroup',
        :'teachers_group' => :'teachersGroup',
        :'issues' => :'issues',
        :'google_classroom' => :'googleClassroom',
        :'google_drive' => :'googleDrive',
        :'microsoft_graph' => :'microsoftGraph',
        :'lti' => :'lti',
        :'canvas' => :'canvas',
        :'mfc' => :'mfc',
        :'clever' => :'clever',
        :'level' => :'level',
        :'skills_focused' => :'skillsFocused',
        :'size' => :'size'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'state' => :'ClassState',
        :'name' => :'String',
        :'section' => :'String',
        :'description' => :'String',
        :'organization' => :'String',
        :'owner' => :'String',
        :'creation_date' => :'Time',
        :'enrollment_code' => :'String',
        :'theme' => :'String',
        :'assignments_count' => :'Float',
        :'students_group' => :'GroupDetails',
        :'teachers_group' => :'GroupDetails',
        :'issues' => :'ClassDetailsIssues',
        :'google_classroom' => :'ClassDetailsGoogleClassroom',
        :'google_drive' => :'ClassDetailsGoogleDrive',
        :'microsoft_graph' => :'ClassDetailsMicrosoftGraph',
        :'lti' => :'ClassDetailsLti',
        :'canvas' => :'ClassDetailsCanvas',
        :'mfc' => :'ClassDetailsMfc',
        :'clever' => :'ClassDetailsClever',
        :'level' => :'ClassGradeLevel',
        :'skills_focused' => :'Array<String>',
        :'size' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'size'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::ClassDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::ClassDetails`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'section')
        self.section = attributes[:'section']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'organization')
        self.organization = attributes[:'organization']
      end

      if attributes.key?(:'owner')
        self.owner = attributes[:'owner']
      end

      if attributes.key?(:'creation_date')
        self.creation_date = attributes[:'creation_date']
      end

      if attributes.key?(:'enrollment_code')
        self.enrollment_code = attributes[:'enrollment_code']
      end

      if attributes.key?(:'theme')
        self.theme = attributes[:'theme']
      end

      if attributes.key?(:'assignments_count')
        self.assignments_count = attributes[:'assignments_count']
      end

      if attributes.key?(:'students_group')
        self.students_group = attributes[:'students_group']
      end

      if attributes.key?(:'teachers_group')
        self.teachers_group = attributes[:'teachers_group']
      end

      if attributes.key?(:'issues')
        self.issues = attributes[:'issues']
      end

      if attributes.key?(:'google_classroom')
        self.google_classroom = attributes[:'google_classroom']
      end

      if attributes.key?(:'google_drive')
        self.google_drive = attributes[:'google_drive']
      end

      if attributes.key?(:'microsoft_graph')
        self.microsoft_graph = attributes[:'microsoft_graph']
      end

      if attributes.key?(:'lti')
        self.lti = attributes[:'lti']
      end

      if attributes.key?(:'canvas')
        self.canvas = attributes[:'canvas']
      end

      if attributes.key?(:'mfc')
        self.mfc = attributes[:'mfc']
      end

      if attributes.key?(:'clever')
        self.clever = attributes[:'clever']
      end

      if attributes.key?(:'level')
        self.level = attributes[:'level']
      end

      if attributes.key?(:'skills_focused')
        if (value = attributes[:'skills_focused']).is_a?(Array)
          self.skills_focused = value
        end
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          state == o.state &&
          name == o.name &&
          section == o.section &&
          description == o.description &&
          organization == o.organization &&
          owner == o.owner &&
          creation_date == o.creation_date &&
          enrollment_code == o.enrollment_code &&
          theme == o.theme &&
          assignments_count == o.assignments_count &&
          students_group == o.students_group &&
          teachers_group == o.teachers_group &&
          issues == o.issues &&
          google_classroom == o.google_classroom &&
          google_drive == o.google_drive &&
          microsoft_graph == o.microsoft_graph &&
          lti == o.lti &&
          canvas == o.canvas &&
          mfc == o.mfc &&
          clever == o.clever &&
          level == o.level &&
          skills_focused == o.skills_focused &&
          size == o.size
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, state, name, section, description, organization, owner, creation_date, enrollment_code, theme, assignments_count, students_group, teachers_group, issues, google_classroom, google_drive, microsoft_graph, lti, canvas, mfc, clever, level, skills_focused, size].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FlatApi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
