=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.26.2
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module FlatApi
  # Collection of scores
  class Collection < ApiModelBase
    # Unique identifier of the collection
    attr_accessor :id

    # The title of the collection
    attr_accessor :title

    # The url where the collection can be viewed in a web browser
    attr_accessor :html_url

    attr_accessor :type

    # Product-specific translation key for the collection type.  Only set for specific collection types: * For `regular` type: `playlist` (Flat) or `collection` (Flat for Education) * For `collaborations` type: `collaboration` (Flat) or `shared-scores` (Flat for Education)  Not set for other collection types. 
    attr_accessor :label_key

    attr_accessor :privacy

    # The private sharing key of the collection (available when the `privacy` mode is set to `privateLink`)
    attr_accessor :sharing_key

    attr_accessor :app

    # The date when the collection was created
    attr_accessor :creation_date

    # The date when the collection was last modified
    attr_accessor :modification_date

    attr_accessor :user

    # If the score has been created in an organization, the identifier of this organization.  
    attr_accessor :organization

    attr_accessor :rights

    # The list of the collaborators of the collection
    attr_accessor :collaborators

    # Whether the collection is pinned by the owner
    attr_accessor :is_pinned

    attr_accessor :contents

    attr_accessor :capabilities

    # The list of parent collections this score is included in. Please note that you might not have access to all of them.
    attr_accessor :collections

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'title' => :'title',
        :'html_url' => :'htmlUrl',
        :'type' => :'type',
        :'label_key' => :'labelKey',
        :'privacy' => :'privacy',
        :'sharing_key' => :'sharingKey',
        :'app' => :'app',
        :'creation_date' => :'creationDate',
        :'modification_date' => :'modificationDate',
        :'user' => :'user',
        :'organization' => :'organization',
        :'rights' => :'rights',
        :'collaborators' => :'collaborators',
        :'is_pinned' => :'isPinned',
        :'contents' => :'contents',
        :'capabilities' => :'capabilities',
        :'collections' => :'collections'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'title' => :'String',
        :'html_url' => :'String',
        :'type' => :'CollectionType',
        :'label_key' => :'String',
        :'privacy' => :'CollectionPrivacy',
        :'sharing_key' => :'String',
        :'app' => :'CollectionApp',
        :'creation_date' => :'Time',
        :'modification_date' => :'Time',
        :'user' => :'UserPublicSummary',
        :'organization' => :'String',
        :'rights' => :'ResourceRights',
        :'collaborators' => :'Array<ResourceCollaborator>',
        :'is_pinned' => :'Boolean',
        :'contents' => :'CollectionContents',
        :'capabilities' => :'CollectionCapabilities',
        :'collections' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::Collection` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::Collection`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'html_url')
        self.html_url = attributes[:'html_url']
      else
        self.html_url = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'label_key')
        self.label_key = attributes[:'label_key']
      end

      if attributes.key?(:'privacy')
        self.privacy = attributes[:'privacy']
      else
        self.privacy = 'private'
      end

      if attributes.key?(:'sharing_key')
        self.sharing_key = attributes[:'sharing_key']
      end

      if attributes.key?(:'app')
        self.app = attributes[:'app']
      end

      if attributes.key?(:'creation_date')
        self.creation_date = attributes[:'creation_date']
      else
        self.creation_date = nil
      end

      if attributes.key?(:'modification_date')
        self.modification_date = attributes[:'modification_date']
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'organization')
        self.organization = attributes[:'organization']
      end

      if attributes.key?(:'rights')
        self.rights = attributes[:'rights']
      end

      if attributes.key?(:'collaborators')
        if (value = attributes[:'collaborators']).is_a?(Array)
          self.collaborators = value
        end
      end

      if attributes.key?(:'is_pinned')
        self.is_pinned = attributes[:'is_pinned']
      end

      if attributes.key?(:'contents')
        self.contents = attributes[:'contents']
      else
        self.contents = nil
      end

      if attributes.key?(:'capabilities')
        self.capabilities = attributes[:'capabilities']
      else
        self.capabilities = nil
      end

      if attributes.key?(:'collections')
        if (value = attributes[:'collections']).is_a?(Array)
          self.collections = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @html_url.nil?
        invalid_properties.push('invalid value for "html_url", html_url cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @privacy.nil?
        invalid_properties.push('invalid value for "privacy", privacy cannot be nil.')
      end

      if @creation_date.nil?
        invalid_properties.push('invalid value for "creation_date", creation_date cannot be nil.')
      end

      if @contents.nil?
        invalid_properties.push('invalid value for "contents", contents cannot be nil.')
      end

      if @capabilities.nil?
        invalid_properties.push('invalid value for "capabilities", capabilities cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @title.nil?
      return false if @html_url.nil?
      return false if @type.nil?
      return false if @privacy.nil?
      return false if @creation_date.nil?
      return false if @contents.nil?
      return false if @capabilities.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] html_url Value to be assigned
    def html_url=(html_url)
      if html_url.nil?
        fail ArgumentError, 'html_url cannot be nil'
      end

      @html_url = html_url
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] privacy Value to be assigned
    def privacy=(privacy)
      if privacy.nil?
        fail ArgumentError, 'privacy cannot be nil'
      end

      @privacy = privacy
    end

    # Custom attribute writer method with validation
    # @param [Object] creation_date Value to be assigned
    def creation_date=(creation_date)
      if creation_date.nil?
        fail ArgumentError, 'creation_date cannot be nil'
      end

      @creation_date = creation_date
    end

    # Custom attribute writer method with validation
    # @param [Object] contents Value to be assigned
    def contents=(contents)
      if contents.nil?
        fail ArgumentError, 'contents cannot be nil'
      end

      @contents = contents
    end

    # Custom attribute writer method with validation
    # @param [Object] capabilities Value to be assigned
    def capabilities=(capabilities)
      if capabilities.nil?
        fail ArgumentError, 'capabilities cannot be nil'
      end

      @capabilities = capabilities
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          title == o.title &&
          html_url == o.html_url &&
          type == o.type &&
          label_key == o.label_key &&
          privacy == o.privacy &&
          sharing_key == o.sharing_key &&
          app == o.app &&
          creation_date == o.creation_date &&
          modification_date == o.modification_date &&
          user == o.user &&
          organization == o.organization &&
          rights == o.rights &&
          collaborators == o.collaborators &&
          is_pinned == o.is_pinned &&
          contents == o.contents &&
          capabilities == o.capabilities &&
          collections == o.collections
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, title, html_url, type, label_key, privacy, sharing_key, app, creation_date, modification_date, user, organization, rights, collaborators, is_pinned, contents, capabilities, collections].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
