=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.26.2
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module FlatApi
  # Creation of an education resource
  class EduResourceCreation < ApiModelBase
    attr_accessor :type

    # Title of the resource
    attr_accessor :title

    # Identifier of the parent resource where the new one will be created, e.g. a folder id or `root`
    attr_accessor :parent

    # Sharing description of the resource
    attr_accessor :sharing_description

    # HTML version of sharing description with rich text formatting.  Supports safe HTML tags: p, br, strong, b, em, i, u, a. 
    attr_accessor :sharing_description_html

    attr_accessor :resource

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'title' => :'title',
        :'parent' => :'parent',
        :'sharing_description' => :'sharingDescription',
        :'sharing_description_html' => :'sharingDescriptionHtml',
        :'resource' => :'resource'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'EduResourceType',
        :'title' => :'String',
        :'parent' => :'String',
        :'sharing_description' => :'String',
        :'sharing_description_html' => :'String',
        :'resource' => :'EduResourceAssignmentCreation'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::EduResourceCreation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::EduResourceCreation`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'parent')
        self.parent = attributes[:'parent']
      else
        self.parent = 'root'
      end

      if attributes.key?(:'sharing_description')
        self.sharing_description = attributes[:'sharing_description']
      end

      if attributes.key?(:'sharing_description_html')
        self.sharing_description_html = attributes[:'sharing_description_html']
      end

      if attributes.key?(:'resource')
        self.resource = attributes[:'resource']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @title.to_s.length > 1000
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 1000.')
      end

      if @title.to_s.length < 1
        invalid_properties.push('invalid value for "title", the character length must be greater than or equal to 1.')
      end

      if !@sharing_description.nil? && @sharing_description.to_s.length > 400
        invalid_properties.push('invalid value for "sharing_description", the character length must be smaller than or equal to 400.')
      end

      if !@sharing_description_html.nil? && @sharing_description_html.to_s.length > 10000
        invalid_properties.push('invalid value for "sharing_description_html", the character length must be smaller than or equal to 10000.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      return false if @title.nil?
      return false if @title.to_s.length > 1000
      return false if @title.to_s.length < 1
      return false if !@sharing_description.nil? && @sharing_description.to_s.length > 400
      return false if !@sharing_description_html.nil? && @sharing_description_html.to_s.length > 10000
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      if title.to_s.length > 1000
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 1000.'
      end

      if title.to_s.length < 1
        fail ArgumentError, 'invalid value for "title", the character length must be greater than or equal to 1.'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] sharing_description Value to be assigned
    def sharing_description=(sharing_description)
      if sharing_description.nil?
        fail ArgumentError, 'sharing_description cannot be nil'
      end

      if sharing_description.to_s.length > 400
        fail ArgumentError, 'invalid value for "sharing_description", the character length must be smaller than or equal to 400.'
      end

      @sharing_description = sharing_description
    end

    # Custom attribute writer method with validation
    # @param [Object] sharing_description_html Value to be assigned
    def sharing_description_html=(sharing_description_html)
      if sharing_description_html.nil?
        fail ArgumentError, 'sharing_description_html cannot be nil'
      end

      if sharing_description_html.to_s.length > 10000
        fail ArgumentError, 'invalid value for "sharing_description_html", the character length must be smaller than or equal to 10000.'
      end

      @sharing_description_html = sharing_description_html
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          title == o.title &&
          parent == o.parent &&
          sharing_description == o.sharing_description &&
          sharing_description_html == o.sharing_description_html &&
          resource == o.resource
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, title, parent, sharing_description, sharing_description_html, resource].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
