=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.26.2
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module FlatApi
  class LtiConfiguration1p3Dynamic < ApiModelBase
    # Configuration ID
    attr_accessor :id

    # LTI version (1.3)
    attr_accessor :lti_version

    # Organization ID
    attr_accessor :organization_id

    # Organization name
    attr_accessor :organization_name

    # ID of the user who created this configuration
    attr_accessor :creator_id

    # Configuration creation date
    attr_accessor :creation_date

    # Last time this configuration was used
    attr_accessor :last_used_date

    # Configuration status indicator
    attr_accessor :status

    # Dynamic registration LTI 1.3 configuration mode
    attr_accessor :mode

    # Platform issuer URL
    attr_accessor :platform_iss

    # Platform display name
    attr_accessor :platform_name

    # OAuth2 client_id allocated by the platform
    attr_accessor :client_id

    # Deployment ID linking the tool to a tenant/class (varies by platform)
    attr_accessor :deployment_id

    # OAuth2 token endpoint (for AGS/NRPS)
    attr_accessor :access_token_url

    # OIDC authorization/login endpoint
    attr_accessor :authorization_url

    # Platform JWKS endpoint (public keys)
    attr_accessor :jwks_url

    # Deployment mode (single for organization-specific, multi for shared parent platforms)
    attr_accessor :deployment_mode

    attr_accessor :supported_services

    attr_accessor :tool

    # Public keyset URL for the platform to retrieve Flat's public keys
    attr_accessor :public_keyset_url

    # URL for the platform to initiate LTI login
    attr_accessor :initiate_login_url

    # Allowed redirect URIs for LTI launches
    attr_accessor :redirect_uris

    # Enable email-based user matching during LTI authentication.  When true (default): If a user with the same email exists in the organization, they will be matched and logged in instead of creating a new account.  When false: Email matching is disabled. Only LTI ID matching is used, which means multiple LTI users can share the same email address and have separate Flat accounts. This is useful for cases like siblings sharing a parent email in the LMS. 
    attr_accessor :enable_email_matching

    # Only included for admins
    attr_accessor :registration_token

    # Dynamic registration URL (only included for admins when available)
    attr_accessor :registration_url

    # Whether dynamic registration token has been used
    attr_accessor :registration_token_used

    # Date when dynamic registration completed (null when not completed)
    attr_accessor :registration_completion_date

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'lti_version' => :'ltiVersion',
        :'organization_id' => :'organizationId',
        :'organization_name' => :'organizationName',
        :'creator_id' => :'creatorId',
        :'creation_date' => :'creationDate',
        :'last_used_date' => :'lastUsedDate',
        :'status' => :'status',
        :'mode' => :'mode',
        :'platform_iss' => :'platformIss',
        :'platform_name' => :'platformName',
        :'client_id' => :'clientId',
        :'deployment_id' => :'deploymentId',
        :'access_token_url' => :'accessTokenUrl',
        :'authorization_url' => :'authorizationUrl',
        :'jwks_url' => :'jwksUrl',
        :'deployment_mode' => :'deploymentMode',
        :'supported_services' => :'supportedServices',
        :'tool' => :'tool',
        :'public_keyset_url' => :'publicKeysetUrl',
        :'initiate_login_url' => :'initiateLoginUrl',
        :'redirect_uris' => :'redirectUris',
        :'enable_email_matching' => :'enableEmailMatching',
        :'registration_token' => :'registrationToken',
        :'registration_url' => :'registrationUrl',
        :'registration_token_used' => :'registrationTokenUsed',
        :'registration_completion_date' => :'registrationCompletionDate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'lti_version' => :'String',
        :'organization_id' => :'String',
        :'organization_name' => :'String',
        :'creator_id' => :'String',
        :'creation_date' => :'Time',
        :'last_used_date' => :'Time',
        :'status' => :'String',
        :'mode' => :'String',
        :'platform_iss' => :'String',
        :'platform_name' => :'String',
        :'client_id' => :'String',
        :'deployment_id' => :'String',
        :'access_token_url' => :'String',
        :'authorization_url' => :'String',
        :'jwks_url' => :'String',
        :'deployment_mode' => :'String',
        :'supported_services' => :'LtiConfiguration1p3BaseSupportedServices',
        :'tool' => :'LtiConfiguration1p3BaseTool',
        :'public_keyset_url' => :'String',
        :'initiate_login_url' => :'String',
        :'redirect_uris' => :'Array<String>',
        :'enable_email_matching' => :'Boolean',
        :'registration_token' => :'String',
        :'registration_url' => :'String',
        :'registration_token_used' => :'Boolean',
        :'registration_completion_date' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'registration_completion_date'
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'LtiConfiguration1p3Base',
      :'LtiConfigurationBase'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::LtiConfiguration1p3Dynamic` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::LtiConfiguration1p3Dynamic`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'lti_version')
        self.lti_version = attributes[:'lti_version']
      else
        self.lti_version = nil
      end

      if attributes.key?(:'organization_id')
        self.organization_id = attributes[:'organization_id']
      end

      if attributes.key?(:'organization_name')
        self.organization_name = attributes[:'organization_name']
      end

      if attributes.key?(:'creator_id')
        self.creator_id = attributes[:'creator_id']
      end

      if attributes.key?(:'creation_date')
        self.creation_date = attributes[:'creation_date']
      else
        self.creation_date = nil
      end

      if attributes.key?(:'last_used_date')
        self.last_used_date = attributes[:'last_used_date']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      end

      if attributes.key?(:'platform_iss')
        self.platform_iss = attributes[:'platform_iss']
      end

      if attributes.key?(:'platform_name')
        self.platform_name = attributes[:'platform_name']
      end

      if attributes.key?(:'client_id')
        self.client_id = attributes[:'client_id']
      end

      if attributes.key?(:'deployment_id')
        self.deployment_id = attributes[:'deployment_id']
      end

      if attributes.key?(:'access_token_url')
        self.access_token_url = attributes[:'access_token_url']
      end

      if attributes.key?(:'authorization_url')
        self.authorization_url = attributes[:'authorization_url']
      end

      if attributes.key?(:'jwks_url')
        self.jwks_url = attributes[:'jwks_url']
      end

      if attributes.key?(:'deployment_mode')
        self.deployment_mode = attributes[:'deployment_mode']
      end

      if attributes.key?(:'supported_services')
        self.supported_services = attributes[:'supported_services']
      end

      if attributes.key?(:'tool')
        self.tool = attributes[:'tool']
      end

      if attributes.key?(:'public_keyset_url')
        self.public_keyset_url = attributes[:'public_keyset_url']
      end

      if attributes.key?(:'initiate_login_url')
        self.initiate_login_url = attributes[:'initiate_login_url']
      end

      if attributes.key?(:'redirect_uris')
        if (value = attributes[:'redirect_uris']).is_a?(Array)
          self.redirect_uris = value
        end
      end

      if attributes.key?(:'enable_email_matching')
        self.enable_email_matching = attributes[:'enable_email_matching']
      else
        self.enable_email_matching = true
      end

      if attributes.key?(:'registration_token')
        self.registration_token = attributes[:'registration_token']
      end

      if attributes.key?(:'registration_url')
        self.registration_url = attributes[:'registration_url']
      end

      if attributes.key?(:'registration_token_used')
        self.registration_token_used = attributes[:'registration_token_used']
      end

      if attributes.key?(:'registration_completion_date')
        self.registration_completion_date = attributes[:'registration_completion_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @lti_version.nil?
        invalid_properties.push('invalid value for "lti_version", lti_version cannot be nil.')
      end

      if @creation_date.nil?
        invalid_properties.push('invalid value for "creation_date", creation_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @lti_version.nil?
      lti_version_validator = EnumAttributeValidator.new('String', ["1p3"])
      return false unless lti_version_validator.valid?(@lti_version)
      return false if @creation_date.nil?
      status_validator = EnumAttributeValidator.new('String', ["ready-to-use", "in-use", "incomplete-setup"])
      return false unless status_validator.valid?(@status)
      mode_validator = EnumAttributeValidator.new('String', ["1p3-dynamic"])
      return false unless mode_validator.valid?(@mode)
      deployment_mode_validator = EnumAttributeValidator.new('String', ["single", "multi"])
      return false unless deployment_mode_validator.valid?(@deployment_mode)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] lti_version Object to be assigned
    def lti_version=(lti_version)
      validator = EnumAttributeValidator.new('String', ["1p3"])
      unless validator.valid?(lti_version)
        fail ArgumentError, "invalid value for \"lti_version\", must be one of #{validator.allowable_values}."
      end
      @lti_version = lti_version
    end

    # Custom attribute writer method with validation
    # @param [Object] creation_date Value to be assigned
    def creation_date=(creation_date)
      if creation_date.nil?
        fail ArgumentError, 'creation_date cannot be nil'
      end

      @creation_date = creation_date
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ready-to-use", "in-use", "incomplete-setup"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] mode Object to be assigned
    def mode=(mode)
      validator = EnumAttributeValidator.new('String', ["1p3-dynamic"])
      unless validator.valid?(mode)
        fail ArgumentError, "invalid value for \"mode\", must be one of #{validator.allowable_values}."
      end
      @mode = mode
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] deployment_mode Object to be assigned
    def deployment_mode=(deployment_mode)
      validator = EnumAttributeValidator.new('String', ["single", "multi"])
      unless validator.valid?(deployment_mode)
        fail ArgumentError, "invalid value for \"deployment_mode\", must be one of #{validator.allowable_values}."
      end
      @deployment_mode = deployment_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          lti_version == o.lti_version &&
          organization_id == o.organization_id &&
          organization_name == o.organization_name &&
          creator_id == o.creator_id &&
          creation_date == o.creation_date &&
          last_used_date == o.last_used_date &&
          status == o.status &&
          mode == o.mode &&
          platform_iss == o.platform_iss &&
          platform_name == o.platform_name &&
          client_id == o.client_id &&
          deployment_id == o.deployment_id &&
          access_token_url == o.access_token_url &&
          authorization_url == o.authorization_url &&
          jwks_url == o.jwks_url &&
          deployment_mode == o.deployment_mode &&
          supported_services == o.supported_services &&
          tool == o.tool &&
          public_keyset_url == o.public_keyset_url &&
          initiate_login_url == o.initiate_login_url &&
          redirect_uris == o.redirect_uris &&
          enable_email_matching == o.enable_email_matching &&
          registration_token == o.registration_token &&
          registration_url == o.registration_url &&
          registration_token_used == o.registration_token_used &&
          registration_completion_date == o.registration_completion_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, lti_version, organization_id, organization_name, creator_id, creation_date, last_used_date, status, mode, platform_iss, platform_name, client_id, deployment_id, access_token_url, authorization_url, jwks_url, deployment_mode, supported_services, tool, public_keyset_url, initiate_login_url, redirect_uris, enable_email_matching, registration_token, registration_url, registration_token_used, registration_completion_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
