=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.26.1
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module FlatApi
  # What the account or app can do, for client feature-detection.
  class OmrCapabilities < ApiModelBase
    # Interactive steps this server supports.
    attr_accessor :steps

    # Export formats available via `getOmrJobExport`.
    attr_accessor :formats

    # Output destinations the account can use when creating a job.
    attr_accessor :outputs

    # Maximum number of input files that can be added to a single job.
    attr_accessor :max_files

    # Maximum number of pages allowed across all input files of a single job.
    attr_accessor :max_pages

    # Maximum number of OMR jobs that can run in parallel for this account.
    attr_accessor :max_parallel_jobs

    # Maximum size of a single file, in bytes.
    attr_accessor :max_file_size

    # MIME types accepted for input files: PDF, plus the raster image formats.  Drive the file picker from this list rather than hardcoding it, so newly supported formats need no client release. A file is identified by its content, so its declared type and its extension do not have to match.  A multi-page input counts as several pages against `maxPages` and is charged accordingly. That covers PDFs and, among the image formats, multi-page TIFF and animated GIF/WebP. 
    attr_accessor :accepted_mime_types

    # Filename extensions the accepted types appear under, for building a file picker.  Use these alongside `acceptedMimeTypes` in an `accept` attribute: browsers and native file dialogs filter unreliably on some of the image types, so a valid file can be greyed out when only its MIME type is offered.  Longer than `acceptedMimeTypes`, because one type arrives under several extensions (`.jpg` and `.jpeg`, `.tif` and `.tiff`, `.heic` and `.heif`).  Picker metadata only. A file is identified by its content, so its extension never decides whether an upload is accepted. 
    attr_accessor :accepted_extensions

    # Credits charged per page.
    attr_accessor :cost_per_page

    # OMR credits remaining for the account.
    attr_accessor :remaining_credits

    # How many days a `musicxml` job's uploaded files and results are kept before erasure.  Reflects the account's own period when one has been set, otherwise the platform default. Read-only: contact support to change it. Jobs with `output: library` are not covered by the retention policy and are unaffected by this value. 
    attr_accessor :retention_days

    # Locales selectable for OCR, as BCP 47 codes sorted alphabetically.  These are the locales the recognition pipeline can actually read, which is neither the list of Flat interface locales nor a fixed set: new languages are added over time. Clients should default to the user's own locale when it appears here. 
    attr_accessor :locales

    # The same locales as `locales`, each with its English display name, sorted alphabetically by `name` and ready to bind to a language picker.  Prefer this over `locales` when rendering a selector: it saves clients from shipping their own code-to-label table. 
    attr_accessor :locales_details

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'steps' => :'steps',
        :'formats' => :'formats',
        :'outputs' => :'outputs',
        :'max_files' => :'maxFiles',
        :'max_pages' => :'maxPages',
        :'max_parallel_jobs' => :'maxParallelJobs',
        :'max_file_size' => :'maxFileSize',
        :'accepted_mime_types' => :'acceptedMimeTypes',
        :'accepted_extensions' => :'acceptedExtensions',
        :'cost_per_page' => :'costPerPage',
        :'remaining_credits' => :'remainingCredits',
        :'retention_days' => :'retentionDays',
        :'locales' => :'locales',
        :'locales_details' => :'localesDetails'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'steps' => :'Array<OmrStepName>',
        :'formats' => :'Array<String>',
        :'outputs' => :'Array<OmrJobOutput>',
        :'max_files' => :'Integer',
        :'max_pages' => :'Integer',
        :'max_parallel_jobs' => :'Integer',
        :'max_file_size' => :'Integer',
        :'accepted_mime_types' => :'Array<String>',
        :'accepted_extensions' => :'Array<String>',
        :'cost_per_page' => :'Integer',
        :'remaining_credits' => :'Integer',
        :'retention_days' => :'Integer',
        :'locales' => :'Array<String>',
        :'locales_details' => :'Array<OmrLocaleDetails>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::OmrCapabilities` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::OmrCapabilities`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'steps')
        if (value = attributes[:'steps']).is_a?(Array)
          self.steps = value
        end
      else
        self.steps = nil
      end

      if attributes.key?(:'formats')
        if (value = attributes[:'formats']).is_a?(Array)
          self.formats = value
        end
      else
        self.formats = nil
      end

      if attributes.key?(:'outputs')
        if (value = attributes[:'outputs']).is_a?(Array)
          self.outputs = value
        end
      else
        self.outputs = nil
      end

      if attributes.key?(:'max_files')
        self.max_files = attributes[:'max_files']
      else
        self.max_files = nil
      end

      if attributes.key?(:'max_pages')
        self.max_pages = attributes[:'max_pages']
      else
        self.max_pages = nil
      end

      if attributes.key?(:'max_parallel_jobs')
        self.max_parallel_jobs = attributes[:'max_parallel_jobs']
      else
        self.max_parallel_jobs = nil
      end

      if attributes.key?(:'max_file_size')
        self.max_file_size = attributes[:'max_file_size']
      else
        self.max_file_size = nil
      end

      if attributes.key?(:'accepted_mime_types')
        if (value = attributes[:'accepted_mime_types']).is_a?(Array)
          self.accepted_mime_types = value
        end
      else
        self.accepted_mime_types = nil
      end

      if attributes.key?(:'accepted_extensions')
        if (value = attributes[:'accepted_extensions']).is_a?(Array)
          self.accepted_extensions = value
        end
      else
        self.accepted_extensions = nil
      end

      if attributes.key?(:'cost_per_page')
        self.cost_per_page = attributes[:'cost_per_page']
      end

      if attributes.key?(:'remaining_credits')
        self.remaining_credits = attributes[:'remaining_credits']
      end

      if attributes.key?(:'retention_days')
        self.retention_days = attributes[:'retention_days']
      end

      if attributes.key?(:'locales')
        if (value = attributes[:'locales']).is_a?(Array)
          self.locales = value
        end
      else
        self.locales = nil
      end

      if attributes.key?(:'locales_details')
        if (value = attributes[:'locales_details']).is_a?(Array)
          self.locales_details = value
        end
      else
        self.locales_details = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @steps.nil?
        invalid_properties.push('invalid value for "steps", steps cannot be nil.')
      end

      if @formats.nil?
        invalid_properties.push('invalid value for "formats", formats cannot be nil.')
      end

      if @outputs.nil?
        invalid_properties.push('invalid value for "outputs", outputs cannot be nil.')
      end

      if @max_files.nil?
        invalid_properties.push('invalid value for "max_files", max_files cannot be nil.')
      end

      if @max_pages.nil?
        invalid_properties.push('invalid value for "max_pages", max_pages cannot be nil.')
      end

      if @max_parallel_jobs.nil?
        invalid_properties.push('invalid value for "max_parallel_jobs", max_parallel_jobs cannot be nil.')
      end

      if @max_file_size.nil?
        invalid_properties.push('invalid value for "max_file_size", max_file_size cannot be nil.')
      end

      if @accepted_mime_types.nil?
        invalid_properties.push('invalid value for "accepted_mime_types", accepted_mime_types cannot be nil.')
      end

      if @accepted_extensions.nil?
        invalid_properties.push('invalid value for "accepted_extensions", accepted_extensions cannot be nil.')
      end

      if @locales.nil?
        invalid_properties.push('invalid value for "locales", locales cannot be nil.')
      end

      if @locales_details.nil?
        invalid_properties.push('invalid value for "locales_details", locales_details cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @steps.nil?
      return false if @formats.nil?
      return false if @outputs.nil?
      return false if @max_files.nil?
      return false if @max_pages.nil?
      return false if @max_parallel_jobs.nil?
      return false if @max_file_size.nil?
      return false if @accepted_mime_types.nil?
      return false if @accepted_extensions.nil?
      return false if @locales.nil?
      return false if @locales_details.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] steps Value to be assigned
    def steps=(steps)
      if steps.nil?
        fail ArgumentError, 'steps cannot be nil'
      end

      @steps = steps
    end

    # Custom attribute writer method with validation
    # @param [Object] formats Value to be assigned
    def formats=(formats)
      if formats.nil?
        fail ArgumentError, 'formats cannot be nil'
      end

      @formats = formats
    end

    # Custom attribute writer method with validation
    # @param [Object] outputs Value to be assigned
    def outputs=(outputs)
      if outputs.nil?
        fail ArgumentError, 'outputs cannot be nil'
      end

      @outputs = outputs
    end

    # Custom attribute writer method with validation
    # @param [Object] max_files Value to be assigned
    def max_files=(max_files)
      if max_files.nil?
        fail ArgumentError, 'max_files cannot be nil'
      end

      @max_files = max_files
    end

    # Custom attribute writer method with validation
    # @param [Object] max_pages Value to be assigned
    def max_pages=(max_pages)
      if max_pages.nil?
        fail ArgumentError, 'max_pages cannot be nil'
      end

      @max_pages = max_pages
    end

    # Custom attribute writer method with validation
    # @param [Object] max_parallel_jobs Value to be assigned
    def max_parallel_jobs=(max_parallel_jobs)
      if max_parallel_jobs.nil?
        fail ArgumentError, 'max_parallel_jobs cannot be nil'
      end

      @max_parallel_jobs = max_parallel_jobs
    end

    # Custom attribute writer method with validation
    # @param [Object] max_file_size Value to be assigned
    def max_file_size=(max_file_size)
      if max_file_size.nil?
        fail ArgumentError, 'max_file_size cannot be nil'
      end

      @max_file_size = max_file_size
    end

    # Custom attribute writer method with validation
    # @param [Object] accepted_mime_types Value to be assigned
    def accepted_mime_types=(accepted_mime_types)
      if accepted_mime_types.nil?
        fail ArgumentError, 'accepted_mime_types cannot be nil'
      end

      @accepted_mime_types = accepted_mime_types
    end

    # Custom attribute writer method with validation
    # @param [Object] accepted_extensions Value to be assigned
    def accepted_extensions=(accepted_extensions)
      if accepted_extensions.nil?
        fail ArgumentError, 'accepted_extensions cannot be nil'
      end

      @accepted_extensions = accepted_extensions
    end

    # Custom attribute writer method with validation
    # @param [Object] locales Value to be assigned
    def locales=(locales)
      if locales.nil?
        fail ArgumentError, 'locales cannot be nil'
      end

      @locales = locales
    end

    # Custom attribute writer method with validation
    # @param [Object] locales_details Value to be assigned
    def locales_details=(locales_details)
      if locales_details.nil?
        fail ArgumentError, 'locales_details cannot be nil'
      end

      @locales_details = locales_details
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          steps == o.steps &&
          formats == o.formats &&
          outputs == o.outputs &&
          max_files == o.max_files &&
          max_pages == o.max_pages &&
          max_parallel_jobs == o.max_parallel_jobs &&
          max_file_size == o.max_file_size &&
          accepted_mime_types == o.accepted_mime_types &&
          accepted_extensions == o.accepted_extensions &&
          cost_per_page == o.cost_per_page &&
          remaining_credits == o.remaining_credits &&
          retention_days == o.retention_days &&
          locales == o.locales &&
          locales_details == o.locales_details
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [steps, formats, outputs, max_files, max_pages, max_parallel_jobs, max_file_size, accepted_mime_types, accepted_extensions, cost_per_page, remaining_credits, retention_days, locales, locales_details].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
