=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.20.0
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module FlatApi
  # The score and all its details
  class ScoreDetails
    # The unique identifier of the score
    attr_accessor :id

    # The private sharing key of the score (available when the `privacy` mode is set to `privateLink`)
    attr_accessor :sharing_key

    # The title of the score
    attr_accessor :title

    attr_accessor :privacy

    attr_accessor :user

    # The url where the score can be viewed in a web browser
    attr_accessor :html_url

    # Subtitle of the score
    attr_accessor :subtitle

    # Lyricist of the score
    attr_accessor :lyricist

    # Arranger of the score
    attr_accessor :arranger

    # Composer of the score
    attr_accessor :composer

    # Description of the creation
    attr_accessor :description

    # Tags describing the score
    attr_accessor :tags

    attr_accessor :creation_type

    attr_accessor :license

    # Additional license text written on the exported/printed score
    attr_accessor :license_text

    # In seconds, an approximative duration of the score
    attr_accessor :duration_time

    # The number of measures in the score
    attr_accessor :number_measures

    # The main tempo of the score (in QPM)
    attr_accessor :main_tempo_qpm

    # The main key signature of the score (expressed between -7 and 7).
    attr_accessor :main_key_signature

    attr_accessor :rights

    # The list of the collaborators of the score
    attr_accessor :collaborators

    # The date when the score was created
    attr_accessor :creation_date

    # The date of the last revision of the score
    attr_accessor :modification_date

    # The date when the score was published on Flat
    attr_accessor :publication_date

    # The date when the score was highlighted (featured) on our community
    attr_accessor :highlighted_date

    # If the score has been created in an organization, the identifier of this organization. This property is especially used with the score privacy `organizationPublic`. 
    attr_accessor :organization

    # If the score has been forked, the unique identifier of the parent score. 
    attr_accessor :parent_score

    # An array of the instrument identifiers used in the last version of the score. This is mainly used to display a list of the instruments in the Flat's UI or instruments icons. The format of the strings is `{instrument-group}.{instrument-id}`. 
    attr_accessor :instruments

    # An array of the audio samples identifiers used the different score parts. The format of the strings is `{instrument-group}.{sample-id}`. 
    attr_accessor :samples

    # If the user uses Google Drive and the score exists on Google Drive, this field will contain the unique identifier of the Flat score on Google Drive. You can access the document using the url: `https://drive.google.com/open?id={googleDriveFileId}` 
    attr_accessor :google_drive_file_id

    attr_accessor :likes

    attr_accessor :comments

    attr_accessor :views

    attr_accessor :plays

    # The List of parent collections, which includes all the collections this score is included. Please note that you might not have access to all of them.
    attr_accessor :collections

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'sharing_key' => :'sharingKey',
        :'title' => :'title',
        :'privacy' => :'privacy',
        :'user' => :'user',
        :'html_url' => :'htmlUrl',
        :'subtitle' => :'subtitle',
        :'lyricist' => :'lyricist',
        :'arranger' => :'arranger',
        :'composer' => :'composer',
        :'description' => :'description',
        :'tags' => :'tags',
        :'creation_type' => :'creationType',
        :'license' => :'license',
        :'license_text' => :'licenseText',
        :'duration_time' => :'durationTime',
        :'number_measures' => :'numberMeasures',
        :'main_tempo_qpm' => :'mainTempoQpm',
        :'main_key_signature' => :'mainKeySignature',
        :'rights' => :'rights',
        :'collaborators' => :'collaborators',
        :'creation_date' => :'creationDate',
        :'modification_date' => :'modificationDate',
        :'publication_date' => :'publicationDate',
        :'highlighted_date' => :'highlightedDate',
        :'organization' => :'organization',
        :'parent_score' => :'parentScore',
        :'instruments' => :'instruments',
        :'samples' => :'samples',
        :'google_drive_file_id' => :'googleDriveFileId',
        :'likes' => :'likes',
        :'comments' => :'comments',
        :'views' => :'views',
        :'plays' => :'plays',
        :'collections' => :'collections'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'sharing_key' => :'String',
        :'title' => :'String',
        :'privacy' => :'ScorePrivacy',
        :'user' => :'UserPublic',
        :'html_url' => :'String',
        :'subtitle' => :'String',
        :'lyricist' => :'String',
        :'arranger' => :'String',
        :'composer' => :'String',
        :'description' => :'String',
        :'tags' => :'Array<String>',
        :'creation_type' => :'ScoreCreationType',
        :'license' => :'ScoreLicense',
        :'license_text' => :'String',
        :'duration_time' => :'Float',
        :'number_measures' => :'Integer',
        :'main_tempo_qpm' => :'Float',
        :'main_key_signature' => :'Float',
        :'rights' => :'ResourceRights',
        :'collaborators' => :'Array<ResourceCollaborator>',
        :'creation_date' => :'Time',
        :'modification_date' => :'Time',
        :'publication_date' => :'Time',
        :'highlighted_date' => :'Time',
        :'organization' => :'String',
        :'parent_score' => :'String',
        :'instruments' => :'Array<String>',
        :'samples' => :'Array<String>',
        :'google_drive_file_id' => :'String',
        :'likes' => :'ScoreLikesCounts',
        :'comments' => :'ScoreCommentsCounts',
        :'views' => :'ScoreViewsCounts',
        :'plays' => :'ScorePlaysCounts',
        :'collections' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'creation_type',
        :'license',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'ScoreSummary'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::ScoreDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::ScoreDetails`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'sharing_key')
        self.sharing_key = attributes[:'sharing_key']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'privacy')
        self.privacy = attributes[:'privacy']
      else
        self.privacy = 'private'
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      else
        self.user = nil
      end

      if attributes.key?(:'html_url')
        self.html_url = attributes[:'html_url']
      else
        self.html_url = nil
      end

      if attributes.key?(:'subtitle')
        self.subtitle = attributes[:'subtitle']
      end

      if attributes.key?(:'lyricist')
        self.lyricist = attributes[:'lyricist']
      end

      if attributes.key?(:'arranger')
        self.arranger = attributes[:'arranger']
      end

      if attributes.key?(:'composer')
        self.composer = attributes[:'composer']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'creation_type')
        self.creation_type = attributes[:'creation_type']
      end

      if attributes.key?(:'license')
        self.license = attributes[:'license']
      end

      if attributes.key?(:'license_text')
        self.license_text = attributes[:'license_text']
      end

      if attributes.key?(:'duration_time')
        self.duration_time = attributes[:'duration_time']
      end

      if attributes.key?(:'number_measures')
        self.number_measures = attributes[:'number_measures']
      end

      if attributes.key?(:'main_tempo_qpm')
        self.main_tempo_qpm = attributes[:'main_tempo_qpm']
      end

      if attributes.key?(:'main_key_signature')
        self.main_key_signature = attributes[:'main_key_signature']
      end

      if attributes.key?(:'rights')
        self.rights = attributes[:'rights']
      else
        self.rights = nil
      end

      if attributes.key?(:'collaborators')
        if (value = attributes[:'collaborators']).is_a?(Array)
          self.collaborators = value
        end
      else
        self.collaborators = nil
      end

      if attributes.key?(:'creation_date')
        self.creation_date = attributes[:'creation_date']
      else
        self.creation_date = nil
      end

      if attributes.key?(:'modification_date')
        self.modification_date = attributes[:'modification_date']
      end

      if attributes.key?(:'publication_date')
        self.publication_date = attributes[:'publication_date']
      end

      if attributes.key?(:'highlighted_date')
        self.highlighted_date = attributes[:'highlighted_date']
      end

      if attributes.key?(:'organization')
        self.organization = attributes[:'organization']
      end

      if attributes.key?(:'parent_score')
        self.parent_score = attributes[:'parent_score']
      end

      if attributes.key?(:'instruments')
        if (value = attributes[:'instruments']).is_a?(Array)
          self.instruments = value
        end
      else
        self.instruments = nil
      end

      if attributes.key?(:'samples')
        if (value = attributes[:'samples']).is_a?(Array)
          self.samples = value
        end
      else
        self.samples = nil
      end

      if attributes.key?(:'google_drive_file_id')
        self.google_drive_file_id = attributes[:'google_drive_file_id']
      end

      if attributes.key?(:'likes')
        self.likes = attributes[:'likes']
      end

      if attributes.key?(:'comments')
        self.comments = attributes[:'comments']
      end

      if attributes.key?(:'views')
        self.views = attributes[:'views']
      end

      if attributes.key?(:'plays')
        self.plays = attributes[:'plays']
      end

      if attributes.key?(:'collections')
        if (value = attributes[:'collections']).is_a?(Array)
          self.collections = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @privacy.nil?
        invalid_properties.push('invalid value for "privacy", privacy cannot be nil.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @html_url.nil?
        invalid_properties.push('invalid value for "html_url", html_url cannot be nil.')
      end

      if @rights.nil?
        invalid_properties.push('invalid value for "rights", rights cannot be nil.')
      end

      if @collaborators.nil?
        invalid_properties.push('invalid value for "collaborators", collaborators cannot be nil.')
      end

      if @creation_date.nil?
        invalid_properties.push('invalid value for "creation_date", creation_date cannot be nil.')
      end

      if @instruments.nil?
        invalid_properties.push('invalid value for "instruments", instruments cannot be nil.')
      end

      if @samples.nil?
        invalid_properties.push('invalid value for "samples", samples cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @title.nil?
      return false if @privacy.nil?
      return false if @user.nil?
      return false if @html_url.nil?
      return false if @rights.nil?
      return false if @collaborators.nil?
      return false if @creation_date.nil?
      return false if @instruments.nil?
      return false if @samples.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          sharing_key == o.sharing_key &&
          title == o.title &&
          privacy == o.privacy &&
          user == o.user &&
          html_url == o.html_url &&
          subtitle == o.subtitle &&
          lyricist == o.lyricist &&
          arranger == o.arranger &&
          composer == o.composer &&
          description == o.description &&
          tags == o.tags &&
          creation_type == o.creation_type &&
          license == o.license &&
          license_text == o.license_text &&
          duration_time == o.duration_time &&
          number_measures == o.number_measures &&
          main_tempo_qpm == o.main_tempo_qpm &&
          main_key_signature == o.main_key_signature &&
          rights == o.rights &&
          collaborators == o.collaborators &&
          creation_date == o.creation_date &&
          modification_date == o.modification_date &&
          publication_date == o.publication_date &&
          highlighted_date == o.highlighted_date &&
          organization == o.organization &&
          parent_score == o.parent_score &&
          instruments == o.instruments &&
          samples == o.samples &&
          google_drive_file_id == o.google_drive_file_id &&
          likes == o.likes &&
          comments == o.comments &&
          views == o.views &&
          plays == o.plays &&
          collections == o.collections
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, sharing_key, title, privacy, user, html_url, subtitle, lyricist, arranger, composer, description, tags, creation_type, license, license_text, duration_time, number_measures, main_tempo_qpm, main_key_signature, rights, collaborators, creation_date, modification_date, publication_date, highlighted_date, organization, parent_score, instruments, samples, google_drive_file_id, likes, comments, views, plays, collections].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FlatApi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
