=begin
#Flat API

#The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:  * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro, MuseScore, ABC notation, and many other formats * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI) * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.  The Flat API is built on HTTP. Our API is RESTful: it has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/). This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).  You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference are [available on GitHub](https://github.com/FlatIO/api-reference).  Getting Started and learn more:  * [API Overview and introduction](https://flat.io/developers/docs/api/) * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html) * [SDKs](https://flat.io/developers/docs/api/sdks.html) * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html) * [Changelog](https://flat.io/developers/docs/api/changelog.html) 

The version of the OpenAPI document: 2.26.2
Contact: developers@flat.io
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module FlatApi
  # User creation
  class UserCreation < ApiModelBase
    # Username of the new account
    attr_accessor :username

    # First name of the user
    attr_accessor :firstname

    # Last name of the user
    attr_accessor :lastname

    # Email of the new account
    attr_accessor :email

    # Password of the new account
    attr_accessor :password

    # User language. Input values will be automatically normalized to a supported locale code.
    attr_accessor :locale

    # Role of the new account
    attr_accessor :role

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'username' => :'username',
        :'firstname' => :'firstname',
        :'lastname' => :'lastname',
        :'email' => :'email',
        :'password' => :'password',
        :'locale' => :'locale',
        :'role' => :'role'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'username' => :'String',
        :'firstname' => :'String',
        :'lastname' => :'String',
        :'email' => :'String',
        :'password' => :'String',
        :'locale' => :'String',
        :'role' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlatApi::UserCreation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlatApi::UserCreation`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      else
        self.username = nil
      end

      if attributes.key?(:'firstname')
        self.firstname = attributes[:'firstname']
      end

      if attributes.key?(:'lastname')
        self.lastname = attributes[:'lastname']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      else
        self.password = nil
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      else
        self.locale = 'en'
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      else
        self.role = 'user'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @username.nil?
        invalid_properties.push('invalid value for "username", username cannot be nil.')
      end

      if @username.to_s.length > 30
        invalid_properties.push('invalid value for "username", the character length must be smaller than or equal to 30.')
      end

      if @username.to_s.length < 1
        invalid_properties.push('invalid value for "username", the character length must be greater than or equal to 1.')
      end

      if !@firstname.nil? && @firstname.to_s.length > 60
        invalid_properties.push('invalid value for "firstname", the character length must be smaller than or equal to 60.')
      end

      if !@lastname.nil? && @lastname.to_s.length > 60
        invalid_properties.push('invalid value for "lastname", the character length must be smaller than or equal to 60.')
      end

      if @password.nil?
        invalid_properties.push('invalid value for "password", password cannot be nil.')
      end

      if @password.to_s.length > 1000
        invalid_properties.push('invalid value for "password", the character length must be smaller than or equal to 1000.')
      end

      if @password.to_s.length < 6
        invalid_properties.push('invalid value for "password", the character length must be greater than or equal to 6.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @username.nil?
      return false if @username.to_s.length > 30
      return false if @username.to_s.length < 1
      return false if !@firstname.nil? && @firstname.to_s.length > 60
      return false if !@lastname.nil? && @lastname.to_s.length > 60
      return false if @password.nil?
      return false if @password.to_s.length > 1000
      return false if @password.to_s.length < 6
      role_validator = EnumAttributeValidator.new('String', ["user", "teacher", "admin", "accountAdmin"])
      return false unless role_validator.valid?(@role)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] username Value to be assigned
    def username=(username)
      if username.nil?
        fail ArgumentError, 'username cannot be nil'
      end

      if username.to_s.length > 30
        fail ArgumentError, 'invalid value for "username", the character length must be smaller than or equal to 30.'
      end

      if username.to_s.length < 1
        fail ArgumentError, 'invalid value for "username", the character length must be greater than or equal to 1.'
      end

      @username = username
    end

    # Custom attribute writer method with validation
    # @param [Object] firstname Value to be assigned
    def firstname=(firstname)
      if firstname.nil?
        fail ArgumentError, 'firstname cannot be nil'
      end

      if firstname.to_s.length > 60
        fail ArgumentError, 'invalid value for "firstname", the character length must be smaller than or equal to 60.'
      end

      @firstname = firstname
    end

    # Custom attribute writer method with validation
    # @param [Object] lastname Value to be assigned
    def lastname=(lastname)
      if lastname.nil?
        fail ArgumentError, 'lastname cannot be nil'
      end

      if lastname.to_s.length > 60
        fail ArgumentError, 'invalid value for "lastname", the character length must be smaller than or equal to 60.'
      end

      @lastname = lastname
    end

    # Custom attribute writer method with validation
    # @param [Object] password Value to be assigned
    def password=(password)
      if password.nil?
        fail ArgumentError, 'password cannot be nil'
      end

      if password.to_s.length > 1000
        fail ArgumentError, 'invalid value for "password", the character length must be smaller than or equal to 1000.'
      end

      if password.to_s.length < 6
        fail ArgumentError, 'invalid value for "password", the character length must be greater than or equal to 6.'
      end

      @password = password
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] role Object to be assigned
    def role=(role)
      validator = EnumAttributeValidator.new('String', ["user", "teacher", "admin", "accountAdmin"])
      unless validator.valid?(role)
        fail ArgumentError, "invalid value for \"role\", must be one of #{validator.allowable_values}."
      end
      @role = role
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          username == o.username &&
          firstname == o.firstname &&
          lastname == o.lastname &&
          email == o.email &&
          password == o.password &&
          locale == o.locale &&
          role == o.role
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [username, firstname, lastname, email, password, locale, role].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
