name: Ruby Gem

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: google-github-actions/release-please-action@v4
      id: release
      with:
        release-type: ruby
        package-name: contrived_math
        bump-minor-pre-major: true
        version-file: "lib/flat_api/version.rb"
    - uses: actions/checkout@v3
      if: ${{ steps.release.outputs.release_created }}
    - name: Set up Ruby 3.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
      if: ${{ steps.release.outputs.release_created }}
    - name: Run tests
      run: |
        bundle exec rspec
      if: ${{ steps.release.outputs.release_created }}
    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
      if: ${{ steps.release.outputs.release_created }}
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
      if: ${{ steps.release.outputs.release_created }}
